room1 = (
    'MMMMMMMMMMMMMMMMMMMM',
    'MM    M         MM M',
    'M M      M  M      M',
    'M M M    M         M',
    'M M   M MMMM       M',
    'M   M M  M         M',
    'MMM M    M    MM   M',
    'M        M  M      M',
    'M M  M M M        MM',
    'M      M    M   M  M',
    'MMMMMMM        MM  M',
    'M  M       M       M',
    'M  M  MM      M    M',
    'M  M      MM       M',
    'MMMMMMMMMMMMMMMMMMMM',
)


room2 = (
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'MM    M         MM M    M         MM M',
    'M M      M  M       M      M  M      M',
    'M M M    M          M M    M         M',
    'M M   M    M        M   M MMMM       M',
    'M   M M  M            M M  M         M',
    'MMM M    MM   MM   MM M    M    MM   M',
    'M           M              M  M      M',
    'M M  M M M        M M  M M M        MM',
    'M      M    M   M        M    M   M  M',
    'MMMMMMM        MM  MMM   M       MM  M',
    'M  M       M                 M       M',
    'M  M  MM      M      M  MM      M    M',
    'M  M      MM         M      MM       M',
    'M    M      M   MM     M      M   MM M',
    'M M      M  M       M         M      M',
    'M M M               M M    M         M',
    'M M   M M MM        M  MMMMMMM       M',
    'M   M M               M M            M',
    'MMM M    MM   MM   MM M         MM   M',
    'M           M                 M      M',
    'M M  M M M        M M  M M M        MM',
    'M      M    M   M        M    M   M  M',
    'MMMMMMM        MM  MM MM    M     MM M',
    'M  M       M                 M       M',
    'M  M  MM      M      M  MM      M    M',
    'M  M      MM         M      MM       M',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
)
